import type { CreateGameInput } from "@/types/game";

export const SEED_GAMES: CreateGameInput[] = [
  {
    bggId: 174430,
    name: "Gloomhaven",
    yearpublished: 2017,
    minPlayers: 1,
    maxPlayers: 4,
    playingTime: 120,
    minPlayTime: 60,
    maxPlayTime: 120,
    minAge: 14,
    averageWeight: 3.86,
    thumbnail: "https://cf.geekdo-images.com/sZYp_3BTDGjh2unaZfZmuA__thumb/img/veVnEpIuMJg8S_FMCOJMaEKnkDs=/fit-in/200x150/filters:strip_icc()/pic2437871.jpg",
    image: "https://cf.geekdo-images.com/sZYp_3BTDGjh2unaZfZmuA__original/img/l1rdkRq2PjXKtfEhRME_-VRxFPA=/0x0/filters:format(jpeg)/pic2437871.jpg",
    categories: ["Adventure", "Exploration", "Fantasy", "Fighting", "Miniatures"],
    mechanics: ["Action Points", "Campaign / Battle Card Driven", "Cooperative Game", "Hand Management"],
    owned: true,
    favorite: true,
    notes: "Kampagne mit Alex und Lisa gestartet",
    tags: ["expert-game"],
    shelfLocation: "Regal 1, oben",
  },
  {
    bggId: 167791,
    name: "Terraforming Mars",
    yearpublished: 2016,
    minPlayers: 1,
    maxPlayers: 5,
    playingTime: 120,
    minPlayTime: 120,
    maxPlayTime: 120,
    minAge: 12,
    averageWeight: 3.24,
    thumbnail: "https://cf.geekdo-images.com/wg9oOLcsKvDesSUdZQ4rxw__thumb/img/BTxqxgYay5tHJflmZtfFiUJOGpI=/fit-in/200x150/filters:strip_icc()/pic3536616.jpg",
    image: "https://cf.geekdo-images.com/wg9oOLcsKvDesSUdZQ4rxw__original/img/o6KkTnMyIgjIGMjmzJilRh-biog=/0x0/filters:format(jpeg)/pic3536616.jpg",
    categories: ["Economic", "Industry / Manufacturing", "Science Fiction", "Territory Building"],
    mechanics: ["Card Drafting", "Hand Management", "Set Collection", "Tile Placement"],
    owned: true,
    favorite: true,
    tags: ["expert-game"],
    shelfLocation: "Regal 1, oben",
  },
  {
    bggId: 13,
    name: "Catan",
    yearpublished: 1995,
    minPlayers: 3,
    maxPlayers: 4,
    playingTime: 90,
    minPlayTime: 60,
    maxPlayTime: 120,
    minAge: 10,
    averageWeight: 2.32,
    thumbnail: "https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ7H8yw__thumb/img/8a9HeqFydO7Uun_le9bXWPnidcA=/fit-in/200x150/filters:strip_icc()/pic2419375.jpg",
    image: "https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ7H8yw__original/img/o4p6f88SGE899MM4JbZqGUV1qLU=/0x0/filters:format(jpeg)/pic2419375.jpg",
    categories: ["Economic", "Negotiation"],
    mechanics: ["Dice Rolling", "Network and Route Building", "Resource Management", "Trading"],
    owned: true,
    tags: ["good-with-newcomers", "quick-to-explain"],
    shelfLocation: "Regal 2, mitte",
  },
  {
    bggId: 266192,
    name: "Wingspan",
    yearpublished: 2019,
    minPlayers: 1,
    maxPlayers: 5,
    playingTime: 70,
    minPlayTime: 40,
    maxPlayTime: 70,
    minAge: 10,
    averageWeight: 2.45,
    thumbnail: "https://cf.geekdo-images.com/yLZJCVLlIx4c7eJEWUNJ7w__thumb/img/VNToqgS2-pOGU6MuvIkMPKn_y-s=/fit-in/200x150/filters:strip_icc()/pic4458123.jpg",
    image: "https://cf.geekdo-images.com/yLZJCVLlIx4c7eJEWUNJ7w__original/img/cI_t00MNm30KBx-muQajYSEbzjU=/0x0/filters:format(jpeg)/pic4458123.jpg",
    categories: ["Animals", "Card Game", "Educational"],
    mechanics: ["Card Drafting", "Dice Rolling", "Engine Building", "Hand Management"],
    owned: true,
    favorite: true,
    tags: ["good-with-newcomers"],
    shelfLocation: "Regal 2, mitte",
  },
  {
    bggId: 68448,
    name: "7 Wonders",
    yearpublished: 2010,
    minPlayers: 2,
    maxPlayers: 7,
    playingTime: 30,
    minPlayTime: 30,
    maxPlayTime: 30,
    minAge: 10,
    averageWeight: 2.34,
    thumbnail: "https://cf.geekdo-images.com/RvFVTEpnbb4NM7k0IF8V7A__thumb/img/zruHYxY-Fg90FsBjPqoKOkxMkEA=/fit-in/200x150/filters:strip_icc()/pic860217.jpg",
    image: "https://cf.geekdo-images.com/RvFVTEpnbb4NM7k0IF8V7A__original/img/bkd8JEQxLkOkEeJzHyMpP8dchfU=/0x0/filters:format(jpeg)/pic860217.jpg",
    categories: ["Ancient", "Card Game", "City Building", "Civilization"],
    mechanics: ["Card Drafting", "Hand Management", "Set Collection", "Simultaneous Action Selection"],
    owned: true,
    tags: ["quick-to-explain", "party-game"],
    shelfLocation: "Regal 2, unten",
  },
  {
    bggId: 187645,
    name: "Star Wars: Rebellion",
    yearpublished: 2016,
    minPlayers: 2,
    maxPlayers: 4,
    playingTime: 240,
    minPlayTime: 180,
    maxPlayTime: 240,
    minAge: 14,
    averageWeight: 3.65,
    thumbnail: "https://cf.geekdo-images.com/7SrPNGBKg9IIsP4UQpOi8g__thumb/img/GKm55dMeVkMJbFienMBWOnH0k8M=/fit-in/200x150/filters:strip_icc()/pic4325841.jpg",
    image: "https://cf.geekdo-images.com/7SrPNGBKg9IIsP4UQpOi8g__original/img/AGz9OMqjw4YepJQMOnKrfMKhjqs=/0x0/filters:format(jpeg)/pic4325841.jpg",
    categories: ["Civil War", "Miniatures", "Movies / TV / Radio theme", "Science Fiction", "Wargame"],
    mechanics: ["Area Movement", "Dice Rolling", "Hand Management", "Worker Placement"],
    owned: true,
    tags: ["good-for-two", "expert-game"],
    shelfLocation: "Regal 1, unten",
  },
  {
    bggId: 173346,
    name: "7 Wonders Duel",
    yearpublished: 2015,
    minPlayers: 2,
    maxPlayers: 2,
    playingTime: 30,
    minPlayTime: 30,
    maxPlayTime: 30,
    minAge: 10,
    averageWeight: 2.23,
    thumbnail: "https://cf.geekdo-images.com/zdagMskTF7wJBPjX74XsRw__thumb/img/enxCZt0Cn78-rlvmPvGtOej1ios=/fit-in/200x150/filters:strip_icc()/pic2576399.jpg",
    image: "https://cf.geekdo-images.com/zdagMskTF7wJBPjX74XsRw__original/img/j5S4dmFcaJcw4QPROX3VVk5rjTs=/0x0/filters:format(jpeg)/pic2576399.jpg",
    categories: ["Ancient", "Card Game", "City Building", "Civilization"],
    mechanics: ["Card Drafting", "Set Collection"],
    owned: true,
    favorite: true,
    tags: ["good-for-two", "quick-to-explain"],
    shelfLocation: "Regal 2, unten",
  },
  {
    bggId: 291457,
    name: "Gloomhaven: Jaws of the Lion",
    yearpublished: 2020,
    minPlayers: 1,
    maxPlayers: 4,
    playingTime: 75,
    minPlayTime: 30,
    maxPlayTime: 75,
    minAge: 14,
    averageWeight: 3.57,
    thumbnail: "https://cf.geekdo-images.com/l4AB1-LArnbg34Vi0tsEzA__thumb/img/2yc30q1KMnIMMBRjsn6g0GVkwMI=/fit-in/200x150/filters:strip_icc()/pic5055631.jpg",
    image: "https://cf.geekdo-images.com/l4AB1-LArnbg34Vi0tsEzA__original/img/77EjH-GaECbSfl_5__fP9CKfGa0=/0x0/filters:format(jpeg)/pic5055631.jpg",
    categories: ["Adventure", "Exploration", "Fantasy", "Fighting"],
    mechanics: ["Action Points", "Cooperative Game", "Hand Management"],
    owned: true,
    tags: ["expert-game", "good-with-newcomers"],
    shelfLocation: "Regal 1, oben",
    notes: "Guter Einstieg in Gloomhaven-Universum",
  },
  {
    bggId: 30549,
    name: "Pandemic",
    yearpublished: 2008,
    minPlayers: 2,
    maxPlayers: 4,
    playingTime: 45,
    minPlayTime: 45,
    maxPlayTime: 45,
    minAge: 8,
    averageWeight: 2.42,
    thumbnail: "https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXLLjVqA__thumb/img/oqViRj6nVxK3m36NluTxU1PZkrk=/fit-in/200x150/filters:strip_icc()/pic1534148.jpg",
    image: "https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXLLjVqA__original/img/j-pfXGPNx_fdazJk2bBf3MYbhLs=/0x0/filters:format(jpeg)/pic1534148.jpg",
    categories: ["Medical"],
    mechanics: ["Action Points", "Cooperative Game", "Hand Management", "Set Collection", "Trading"],
    owned: true,
    tags: ["good-with-newcomers", "quick-to-explain"],
    shelfLocation: "Regal 2, mitte",
    notes: "Immer ein Hit mit neuen Spielern",
  },
  {
    bggId: 31260,
    name: "Agricola",
    yearpublished: 2007,
    minPlayers: 1,
    maxPlayers: 5,
    playingTime: 150,
    minPlayTime: 30,
    maxPlayTime: 150,
    minAge: 12,
    averageWeight: 3.63,
    thumbnail: "https://cf.geekdo-images.com/dDDo2Hexl80ucK1IlqTk-g__thumb/img/GKQLDvIOLFnNnOKY1rwSJJwzk4o=/fit-in/200x150/filters:strip_icc()/pic831744.jpg",
    image: "https://cf.geekdo-images.com/dDDo2Hexl80ucK1IlqTk-g__original/img/L5bSGlqWCIFpRIpSgjhUMUmAfJQ=/0x0/filters:format(jpeg)/pic831744.jpg",
    categories: ["Animals", "Economic", "Farming"],
    mechanics: ["Card Drafting", "Hand Management", "Worker Placement"],
    owned: true,
    tags: ["expert-game"],
    shelfLocation: "Regal 1, mitte",
  },
  {
    bggId: 148228,
    name: "Splendor",
    yearpublished: 2014,
    minPlayers: 2,
    maxPlayers: 4,
    playingTime: 30,
    minPlayTime: 30,
    maxPlayTime: 30,
    minAge: 10,
    averageWeight: 1.80,
    thumbnail: "https://cf.geekdo-images.com/rwOMxx4q5yuElIvo-1-OFw__thumb/img/Ysjrpknfbcgjmhr4fYSTDnl4tXA=/fit-in/200x150/filters:strip_icc()/pic1904079.jpg",
    image: "https://cf.geekdo-images.com/rwOMxx4q5yuElIvo-1-OFw__original/img/Y5tpPmI_oGk6r21kn9SfJYln-wE=/0x0/filters:format(jpeg)/pic1904079.jpg",
    categories: ["Card Game", "Economic", "Renaissance"],
    mechanics: ["Card Drafting", "Set Collection"],
    owned: true,
    tags: ["good-with-newcomers", "quick-to-explain", "good-for-two"],
    shelfLocation: "Regal 2, unten",
  },
  {
    bggId: 233078,
    name: "Azul",
    yearpublished: 2017,
    minPlayers: 2,
    maxPlayers: 4,
    playingTime: 45,
    minPlayTime: 30,
    maxPlayTime: 45,
    minAge: 8,
    averageWeight: 1.77,
    thumbnail: "https://cf.geekdo-images.com/aPSHJO0d0XOpQR5X-wJonw__thumb/img/8kOUiRSSk7GJUsJlkB-MnW2tOLE=/fit-in/200x150/filters:strip_icc()/pic3718275.jpg",
    image: "https://cf.geekdo-images.com/aPSHJO0d0XOpQR5X-wJonw__original/img/fFnbwgfnGKlkgHMIIxsDMh4tkyk=/0x0/filters:format(jpeg)/pic3718275.jpg",
    categories: ["Abstract Strategy", "Puzzle"],
    mechanics: ["Drafting", "Pattern Building", "Set Collection", "Tile Placement"],
    owned: true,
    tags: ["good-with-newcomers", "quick-to-explain"],
    shelfLocation: "Regal 2, unten",
    notes: "Toll als Einstiegsspiel",
  },
];
